// This file is auto-generated by AssetsPostprocessor.
// Do not modify this file manually.
//
// To regenerate this file manually, select the menu item Tools > LunarFramework > Generate R.cs.
//

using Luna;
using UnityEngine;

namespace R
{
    public static class Audios
    {
        public static AudioClip _10Sec => Resources.Load<AudioClip>("Audio/10sec");
        public static AudioClip _20Sec => Resources.Load<AudioClip>("Audio/20sec");
        public static AudioClip _30Sec => Resources.Load<AudioClip>("Audio/30sec");
        public static AudioClip EntryBgm => Resources.Load<AudioClip>("Audio/entry_bgm");
        public static AudioClip EntryKeySelect => Resources.Load<AudioClip>("Audio/entry_key_select");
        public static AudioClip High => Resources.Load<AudioClip>("Audio/high");
        public static AudioClip KeyBack => Resources.Load<AudioClip>("Audio/key_back");
        public static AudioClip KeyEffect => Resources.Load<AudioClip>("Audio/Key_effect");
        public static AudioClip KeyStart => Resources.Load<AudioClip>("Audio/key_start");
        public static AudioClip KeyTimer => Resources.Load<AudioClip>("Audio/key_timer");
        public static AudioClip Low => Resources.Load<AudioClip>("Audio/low");
        public static AudioClip SendPoker => Resources.Load<AudioClip>("Audio/send_poker");
        public static AudioClip TimerStart => Resources.Load<AudioClip>("Audio/timer_start");
        public static AudioClip Bgm => Resources.Load<AudioClip>("ChristmasThemes/Audio/bgm");
        public static AudioClip BingoSample => Resources.Load<AudioClip>("ChristmasThemes/Audio/bingo_sample");
        public static AudioClip NumberCheckSample => Resources.Load<AudioClip>("ChristmasThemes/Audio/Number_check_sample");
        public static AudioClip NumberRotateSample => Resources.Load<AudioClip>("ChristmasThemes/Audio/Number_rotate_sample");
        public static AudioClip ReachClickSample => Resources.Load<AudioClip>("ChristmasThemes/Audio/Reach_click_sample");
        public static AudioClip WillReachSample => Resources.Load<AudioClip>("ChristmasThemes/Audio/will_reach_sample");
        public static AudioClip Bgm_e6ea512d1f05d1c40aedc30e2fe1911a => Resources.Load<AudioClip>("DefaultTheme/Audio/bgm");
        public static AudioClip BingoSample_036e3a3ade5d09b478525cd9e423797e => Resources.Load<AudioClip>("DefaultTheme/Audio/bingo_sample");
        public static AudioClip NumberCheckSample_3b49a3d79b5ca3140b0ddd91a7aa3bb9 => Resources.Load<AudioClip>("DefaultTheme/Audio/Number_check_sample");
        public static AudioClip NumberRotateSample_48540d9786ab6d24797cff636942d275 => Resources.Load<AudioClip>("DefaultTheme/Audio/Number_rotate_sample");
        public static AudioClip ReachClickSample_ceb3438bd987f114a8c574d0db370fee => Resources.Load<AudioClip>("DefaultTheme/Audio/Reach_click_sample");
        public static AudioClip WillReachSample_ef09911f31966e94ea2e79dba7471311 => Resources.Load<AudioClip>("DefaultTheme/Audio/will_reach_sample");

    }
}