name: Main

on: 
  push:
    # tags:
    #   - "*"
  pull_request:
    branches:
      - main

jobs:
  # Build project
  build:
    name: Build project
    uses: ./.github/workflows/build.yml
    secrets: inherit
        
  # Create Release
  release:
    name: Create Release
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit
