name: Release

on:
  workflow_call:
    inputs:
      tags:
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Download 
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display structure of build files
        run: ls -R artifacts/**/*.*

      # Release
      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/**/*.zip
            artifacts/**/*.apk
          # tag_name: 1.0.0
